spring.profiles:
  active: 4,5,6
  include: 7,8,9

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learn?serverTimezone=UTC
    username: root
    password: hyflearn
hyf:
  hot-refresh:
    server:
      enabled: true
